### ISSUE TITLE
speckle exception when value is space or empty string

### ISSUE THREAD

**Issue by arup-yun** [specklesystems/specklepy#212]
https://github.com/specklesystems/specklepy/blob/d0eb364b3ef45c30182be32448ce5138987b1984/specklepy/objects/base.py#L208

When value is space or empty string will produce error like below. This error occur >50% of the time.

raise SpeckleException(
specklepy.logging.exceptions.SpeckleException: SpeckleException: Could not understand what unit  is referring to. Please enter a valid unit (eg ['mm', 'cm', 'm', 'in', 'ft', 'yd', 'mi']).

resolution:

guard against space or empty string , change to None if necessary.

**Comment by gjedlicska** [comment]
Hello @arup-yun 

could you describe the situation, where this happens 50% of the time? Is this happening when using a Speckle connector?

If the behavior described above is happening in a custom python script, we strongly recommend writing a validator for this. I think hard coding these implicit overrides into our SDK will cause more headache than gain in the long run. 
It can result with undesired outcome ie.: if someone by accident deletes the unit value, the only difference between the good and the bad result can be determined by looking at the data in 2/3D to check the scaling. 
We think on our SDK-s we should fail fast and loud if something has invalid data, so that our users can fix the problems.

On the other hand, Iif this is coming from a connector pls let us know, and we'll fix it.
