### ISSUE TITLE
create odbc transport

### ISSUE THREAD

**Issue by majidaldo** [specklesystems/specklepy#238]
https://github.com/specklesystems/specklepy/blob/67499ab20c754b4f51e8cf3746d4aba745d3af70/src/specklepy/transports/sqlite.py#L10

i don't see anything specific to sqlite in the sqlite transport. should just make it odbc.

**Comment by gjedlicska** [comment]
Hey @majidaldo,

there are a few sqlite specific things in the transport itself, like it uses a `sqlite.Connection` type for its `__connection` attribute and if you check the sql commands in the methods, there are some SQLite specific optimizations there too.

Plus (and this is a big plus) this is how our other SDK(s) are structured, since we use SQLite as a standard local storage mechanism in our Connectors and SKDs.
While technically we could abstract this to an ODBC interface, there is little gain in there for us. If we had other SQL implementation transports, the ODBC transport could arguably act as a common base class, but we don't have any ATM nor is  it on our current radar to add it.

If you have a usecase where this add significant benefits, let us know.
